# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7458812551e12635b12048db3f145bb9878375a12f590fdacfeb22ad477edbb4e3475414e2275bf73e1503c848a8f8b937dd854062125161a8e0c62e159d6b05

test:
  secret_key_base: 3c3dd86a314d16979c6b84339fb01951770f1591eadcbfbb048483179ea09958b04ce337fa3e7563d840ab1d5b9fea3f35c0eeceb54fb5561dd2cd75f35326bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
